"""Unit files: the declared state for each phone, tracked in git.

A unit file is the source of truth. `deploy` pushes it to the device, `pull`
brings back whatever drifted, and `set` writes to both the device and the unit
file so the repository never silently falls behind the hardware.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

RESERVED_KEY_PREFIX = "unit."
DEVICE_CONFIG_PATH = "/data/adb/rackphone/config.env"

SETTING_LINE_PATTERN = re.compile(r"^\s*([A-Za-z0-9_.-]+)\s*=\s*(.*?)\s*$")


def find_repo_root() -> Path:
    """Locate the repository root from an env var, or by walking up from here.

    Returns:
        The repository root, falling back to the current directory.
    """
    override = os.environ.get("RACKPHONE_REPO")
    if override:
        return Path(override).expanduser().resolve()
    for parent in Path(__file__).resolve().parents:
        if (parent / "units").is_dir() and (parent / "modules").is_dir():
            return parent
    return Path.cwd()


def get_units_dir() -> Path:
    """Return the directory holding the tracked unit files.

    Returns:
        Path to `units/` inside the repository.
    """
    return find_repo_root() / "units"


@dataclass
class Unit:
    """The declared state of one phone."""

    name: str
    path: Path
    serial: str | None = None
    label: str = ""
    settings: dict[str, str] = field(default_factory=dict)

    @classmethod
    def load(cls, name: str) -> Unit:
        """Read a unit file from the repository.

        Args:
            name: Unit name, without the `.env` suffix.

        Returns:
            The parsed unit.

        Raises:
            FileNotFoundError: If no unit file with that name exists.
        """
        path = get_units_dir() / f"{name}.env"
        if not path.is_file():
            known = ", ".join(unit.name for unit in load_all_units()) or "none"
            raise FileNotFoundError(f"no unit file for {name!r} (have: {known})")

        unit = cls(name=name, path=path)
        for line in path.read_text().splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            match = SETTING_LINE_PATTERN.match(line)
            if not match:
                continue
            key, value = match.group(1), match.group(2)
            if key == "unit.serial":
                unit.serial = value or None
            elif key == "unit.label":
                unit.label = value
            elif not key.startswith(RESERVED_KEY_PREFIX):
                unit.settings[key] = value
        return unit

    def save(self) -> None:
        """Write the unit back to its file in the repository."""
        lines = [
            f"# Rackphone unit: {self.name}",
            "#",
            "# Declared state for this device. `rackphone deploy` pushes it;",
            "# `rackphone set` updates it alongside the live override so that",
            "# the repo and the hardware do not drift apart.",
            "",
            f"unit.serial={self.serial or ''}",
            f"unit.label={self.label}",
            "",
        ]
        lines += [f"{key}={self.settings[key]}" for key in sorted(self.settings)]
        self.path.write_text("\n".join(lines) + "\n")

    def set_setting(self, key: str, value: str) -> None:
        """Record a setting value.

        Args:
            key: Fully qualified `plugin.key` name.
            value: Value to store.
        """
        self.settings[key] = value

    def remove_setting(self, key: str) -> None:
        """Drop a setting so the device falls back to its default.

        Args:
            key: Fully qualified `plugin.key` name.
        """
        self.settings.pop(key, None)

    def to_device_config(self) -> str:
        """Render the settings as the config file the device reads.

        Returns:
            The contents of `config.env` for this unit.
        """
        header = [
            "# Generated by `rackphone deploy` - do not edit on the device.",
            f"# Unit: {self.name}",
            "",
        ]
        body = [f"{key}={self.settings[key]}" for key in sorted(self.settings)]
        return "\n".join(header + body) + "\n"


def load_all_units() -> list[Unit]:
    """Load every unit file in the repository.

    Returns:
        The units that could be parsed, sorted by file name.
    """
    directory = get_units_dir()
    if not directory.is_dir():
        return []

    units: list[Unit] = []
    for path in sorted(directory.glob("*.env")):
        try:
            units.append(Unit.load(path.stem))
        except (OSError, UnicodeDecodeError, ValueError):
            # A malformed file must not hide the healthy ones.
            continue
    return units


def create_unit(name: str, serial: str, label: str = "") -> Unit:
    """Create a unit file for a connected device.

    Args:
        name: Unit name to adopt the device under.
        serial: adb serial of the device.
        label: Human-readable description of where the phone sits.

    Returns:
        The unit that was written.
    """
    units_dir = get_units_dir()
    units_dir.mkdir(parents=True, exist_ok=True)
    unit = Unit(
        name=name,
        path=units_dir / f"{name}.env",
        serial=serial,
        label=label,
    )
    unit.save()
    return unit
