"""Unit files: the declared state for each phone, tracked in git.

A unit file is the source of truth. `deploy` pushes it to the device, `pull`
brings back whatever drifted. Live overrides made with `set` are written to both
the device and the unit file in the same breath, so the repo does not silently
fall behind the hardware.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

RESERVED_PREFIX = "unit."
DEVICE_CONFIG = "/data/adb/rackphone/config.env"

_LINE = re.compile(r"^\s*([A-Za-z0-9_.-]+)\s*=\s*(.*?)\s*$")


def repo_root() -> Path:
    """Locate the repository from an env var, or by walking up from this file."""
    override = os.environ.get("RACKPHONE_REPO")
    if override:
        return Path(override).expanduser().resolve()
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "units").is_dir() and (parent / "modules").is_dir():
            return parent
    return Path.cwd()


def units_dir() -> Path:
    return repo_root() / "units"


@dataclass
class Unit:
    name: str
    path: Path
    serial: str | None = None
    label: str = ""
    settings: dict[str, str] = field(default_factory=dict)

    @classmethod
    def load(cls, name: str) -> "Unit":
        path = units_dir() / f"{name}.env"
        if not path.is_file():
            known = ", ".join(u.name for u in all_units()) or "none"
            raise FileNotFoundError(f"no unit file for {name!r} (have: {known})")
        unit = cls(name=name, path=path)
        for line in path.read_text().splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            match = _LINE.match(line)
            if not match:
                continue
            key, value = match.group(1), match.group(2)
            if key == "unit.serial":
                unit.serial = value or None
            elif key == "unit.label":
                unit.label = value
            elif key.startswith(RESERVED_PREFIX):
                continue
            else:
                unit.settings[key] = value
        return unit

    def save(self) -> None:
        lines = [
            f"# Rackphone unit: {self.name}",
            "#",
            "# Declared state for this device. `rackphone deploy` pushes it;",
            "# `rackphone set` updates it alongside the live override so that",
            "# the repo and the hardware do not drift apart.",
            "",
            f"unit.serial={self.serial or ''}",
            f"unit.label={self.label}",
            "",
        ]
        for key in sorted(self.settings):
            lines.append(f"{key}={self.settings[key]}")
        self.path.write_text("\n".join(lines) + "\n")

    def set(self, key: str, value: str) -> None:
        self.settings[key] = value

    def unset(self, key: str) -> None:
        self.settings.pop(key, None)

    def to_device_config(self) -> str:
        header = [
            "# Generated by `rackphone deploy` - do not edit on the device.",
            f"# Unit: {self.name}",
            "",
        ]
        body = [f"{k}={self.settings[k]}" for k in sorted(self.settings)]
        return "\n".join(header + body) + "\n"


def all_units() -> list[Unit]:
    directory = units_dir()
    if not directory.is_dir():
        return []
    found = []
    for path in sorted(directory.glob("*.env")):
        try:
            found.append(Unit.load(path.stem))
        except Exception:  # a malformed file should not hide the healthy ones
            continue
    return found


def create_unit(name: str, serial: str, label: str = "") -> Unit:
    units_dir().mkdir(parents=True, exist_ok=True)
    unit = Unit(name=name, path=units_dir() / f"{name}.env", serial=serial, label=label)
    unit.save()
    return unit
